// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUyDeNvmKdOwfhRFBU55tzdQE7MHmcAOs',
    appId: '1:516644085951:web:79620974f154060318660a',
    messagingSenderId: '516644085951',
    projectId: 'cafetarium-database',
    authDomain: 'cafetarium-database.firebaseapp.com',
    storageBucket: 'cafetarium-database.firebasestorage.app',
    measurementId: 'G-VYS3YG5J1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFuGSFpDZRzZXixbj6dD43kEmFJT4-j94',
    appId: '1:516644085951:android:c14662e729f9e14618660a',
    messagingSenderId: '516644085951',
    projectId: 'cafetarium-database',
    storageBucket: 'cafetarium-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDEAcIZy-vSqLqkmkoo39_pr3XbMHJ9Q',
    appId: '1:516644085951:ios:cba74c9f6de96bd518660a',
    messagingSenderId: '516644085951',
    projectId: 'cafetarium-database',
    storageBucket: 'cafetarium-database.firebasestorage.app',
    iosBundleId: 'com.example.cafetarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWDEAcIZy-vSqLqkmkoo39_pr3XbMHJ9Q',
    appId: '1:516644085951:ios:cba74c9f6de96bd518660a',
    messagingSenderId: '516644085951',
    projectId: 'cafetarium-database',
    storageBucket: 'cafetarium-database.firebasestorage.app',
    iosBundleId: 'com.example.cafetarium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUyDeNvmKdOwfhRFBU55tzdQE7MHmcAOs',
    appId: '1:516644085951:web:2eff4aa34f75090918660a',
    messagingSenderId: '516644085951',
    projectId: 'cafetarium-database',
    authDomain: 'cafetarium-database.firebaseapp.com',
    storageBucket: 'cafetarium-database.firebasestorage.app',
    measurementId: 'G-Z20VE8Q2EG',
  );
}
